# Compatibility shim generated by V111.8 final cover package.
# Canonical module: intelligence.knowledge_memory.legacy_daily_memory
from intelligence.knowledge_memory.legacy_daily_memory import *  # noqa: F401,F403
