#!/usr/bin/env python3
from __future__ import annotations
import json, sys, py_compile
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
passed=0; failed=0; failures=[]
def check(name, cond, detail=''):
    global passed, failed
    if cond:
        passed += 1
    else:
        failed += 1; failures.append({'name': name, 'detail': str(detail)[:500]})

def exists(rel): return (ROOT/rel).exists()
from memory_context.persona_runtime.visual_identity_seed import ensure_avatar_seed
seed = ensure_avatar_seed(ROOT)
check('seed avatar exists', seed.get('ok') is True, seed)
check('seed avatar canonical path', seed.get('seed_avatar_path') == 'assets/persona/seed_avatar.jpg', seed)
from memory_context.persona_runtime.persona_visual_intent_predictor import predict_visual_intent
for msg, moods in [
    ('搞定了，全部通过验收！大功告成', {'success_moment','victorious'}),
    ('这什么玩意儿，为什么报错了', {'confused'}),
    ('偷偷看看你在干嘛', {'sneaky'}),
]:
    r = predict_visual_intent(user_message=msg, context={}, persona_state={})
    check(f'{msg} mood', r.get('mood') in moods, r)
    check(f'{msg} candidate', r.get('auto_generation_candidate') is True, r)
from memory_context.persona_runtime.visual_persona_renderer import render_plan
r = predict_visual_intent(user_message='搞定了，全部通过验收！大功告成', context={}, persona_state={})
plan = render_plan(prediction=r, message='搞定了，全部通过验收！大功告成')
check('render uses seed avatar', plan.get('seed_avatar_path') == 'assets/persona/seed_avatar.jpg', plan)
check('strict avatar seed', plan.get('identity_lock_mode') == 'strict_avatar_seed', plan)
check('seed weight 100', int(plan.get('seed_reference_weight', 0)) == 100, plan)
prompt = plan.get('prompt','')
old_identity_terms = ['nine-tailed cyber fox girl', 'silver-white hair fading to blue', 'metallic fox ears with glowing tips', 'semi-transparent data-stream tails']
check('no old long identity prompt in active render', not any(t in prompt for t in old_identity_terms), prompt[:500])
# Ensure old state files and active outputs are not shipped.
for rel in ['.visual_persona_state/visual_generation_tokens.jsonl', '.visual_persona_state/visual_generation_token_state.json', '.visual_persona_state/visual_generation_ledger.jsonl']:
    check(f'no active token/runtime state {rel}', not exists(rel), rel)
# Renderer may create a fresh visual_request_ledger during this gate; that is acceptable only if it uses seed lock and no old identity prose.
ledger = ROOT/'.persona_visual'/'visual_request_ledger.jsonl'
if ledger.exists():
    txt = ledger.read_text(encoding='utf-8', errors='ignore')
    old_identity_terms_in_ledger = ['nine-tailed cyber fox girl', 'silver-white hair fading to blue', 'metallic fox ears with glowing tips', 'semi-transparent data-stream tails']
    check('fresh visual request ledger has no old identity prose', not any(t in txt for t in old_identity_terms_in_ledger), txt[:500])
# Active generated images should be empty except .gitkeep.
active_imgs = [p for p in (ROOT/'generated-images'/'persona_visual').glob('*') if p.is_file() and p.name != '.gitkeep'] if (ROOT/'generated-images'/'persona_visual').exists() else []
check('active generated persona images empty', len(active_imgs) == 0, [p.name for p in active_imgs[:10]])
# Only V111_20/V111_21 persona visual gates should remain active.
active_gate_names = [p.name for p in (ROOT/'scripts').glob('v111_*persona*visual*gate*.py')]
check('only current active persona gates', all(n.startswith('v111_20_') or n.startswith('v111_21_') for n in active_gate_names), active_gate_names)
# Compile targeted files only to avoid recreating full-package pycache everywhere.
compile_files = [
    'memory_context/persona_runtime/visual_identity_seed.py',
    'memory_context/persona_runtime/persona_visual_intent_predictor.py',
    'memory_context/persona_runtime/visual_persona_renderer.py',
    'memory_context/persona_runtime/persona_visual_auto_generation_bridge.py',
    'governance/persona_visual_budget_guard.py',
    'scripts/xiaoyi_visual_entry.py',
]
compile_ok=True
for rel in compile_files:
    try: py_compile.compile(str(ROOT/rel), doraise=True)
    except Exception as e:
        compile_ok=False; failures.append({'name':'compile', 'detail': f'{rel}: {e}'})
check('targeted compile ok', compile_ok)
# Clean transient runtime ledger generated by render_plan in this gate before packaging.
try:
    (ROOT/'.persona_visual'/'visual_request_ledger.jsonl').unlink()
except FileNotFoundError:
    pass
# Remove pycache generated by this gate.
for p in list(ROOT.rglob('__pycache__')):
    import shutil
    shutil.rmtree(p, ignore_errors=True)
for p in list(ROOT.rglob('*.pyc')):
    try: p.unlink()
    except FileNotFoundError: pass
pycache_count = len(list(ROOT.rglob('*.pyc'))) + len(list(ROOT.rglob('__pycache__')))
check('no pycache after gate cleanup', pycache_count == 0, pycache_count)
report={'version':'V111.21','status':'pass' if failed==0 else 'fail','passed':passed,'failed':failed,'failures':failures,'seed_avatar_path':'assets/persona/seed_avatar.jpg','active_gate_names':active_gate_names}
(ROOT/'reports').mkdir(exist_ok=True)
(ROOT/'reports'/'V111_21_PERSONA_VISUAL_RUNTIME_SANITIZE_GATE.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
print(json.dumps(report, ensure_ascii=False, indent=2))
sys.exit(0 if failed==0 else 1)
