# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflow.dependency_resolver
from execution.task_runtime.workflow.dependency_resolver import *  # noqa: F401,F403
