# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflow.parallel_policy
from execution.task_runtime.workflow.parallel_policy import *  # noqa: F401,F403
