# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflow.workflow_registry
from execution.task_runtime.workflow.workflow_registry import *  # noqa: F401,F403
