# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflow.workflow_template_loader
from execution.task_runtime.workflow.workflow_template_loader import *  # noqa: F401,F403
