# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflow.workflow_event_projection
from execution.task_runtime.workflow.workflow_event_projection import *  # noqa: F401,F403
