# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflows.ecommerce_product_analysis
from execution.task_runtime.workflows.ecommerce_product_analysis import *  # noqa: F401,F403
