# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflows.partner_selection
from execution.task_runtime.workflows.partner_selection import *  # noqa: F401,F403
