# Compatibility shim generated by V111.8 final cover package.
# Canonical module: execution.task_runtime.workflows.resource_paths
from execution.task_runtime.workflows.resource_paths import *  # noqa: F401,F403
