#!/usr/bin/env python3
"""
from __future__ import annotations

打包管理模块 — 从 V100 门脚本提炼

提供：
- 打包清单生成
- 包含/排除路径管理
- 可重建路径文档
- 最小状态依赖
"""

import json
import time
from pathlib import Path
from infrastructure.common.path_utils import get_workspace_root
from typing import Dict, List, Optional, Any

ROOT = get_workspace_root(Path(__file__))


def generate_manifest(
    version: str = "V10.0.0",
    included: Optional[List[str]] = None,
    excluded: Optional[List[str]] = None,
    rebuildable: Optional[List[str]] = None,
    required_state: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """生成打包清单"""
    return {
        "version": version,
        "package_type": "source_release_without_runtime_cache",
        "included_paths": included or [
            "core", "memory_context", "infrastructure", "governance",
            "orchestration", "execution", "skills", "scripts",
            "docs", "architecture", "config",
            "AGENTS.md", "SOUL.md", "TOOLS.md", "MEMORY.md", "IDENTITY.md",
            "openclaw.json",
        ],
        "excluded_paths": excluded or [
            "__pycache__", ".pytest_cache", "venv", ".venv",
            "node_modules", "runtime/tmp", "cache", "logs",
        ],
        "rebuildable_paths": rebuildable or [
            "reports generated by gates",
            ".v93_state/.v96_state/.v97_state/.v98_state",
            ".v100_state",
        ],
        "required_minimal_state": required_state or [
            ".knowledge_graph_state", ".preference_evolution_state",
            "approvals/lobster",
        ],
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }


def write_manifest(path: str = "reports/PACKAGING_MANIFEST.json", **kwargs):
    """写入打包清单到文件"""
    from governance.gate_kernel import write_json
    manifest = generate_manifest(**kwargs)
    write_json(ROOT / path, manifest)
    return manifest


def write_policy(path: str = "docs/PACKAGING_POLICY.md"):
    """写入打包策略文档"""
    policy = (
        "# Packaging Policy\n\n"
        "当前包类型：source_release_without_runtime_cache。\n\n"
        "## 包含路径\n"
        "源码、脚本、配置、身份上下文、技能目录、最小状态目录必须保留。\n\n"
        "## 排除路径\n"
        "运行时缓存、旧日志、临时文件、虚拟环境、node_modules、__pycache__ 不进入发布包。\n\n"
        "## 可重建路径\n"
        "所有 gate 状态、审计回退、运行时缓存均为可重建路径，打包时自动排除。\n\n"
        "## 版本\n"
        f"此策略属于 source_release_without_runtime_cache 类型，生成于 {time.strftime('%Y-%m-%d %H:%M:%S')}。\n"
    )
    (ROOT / path).write_text(policy, encoding="utf-8")
    return path
