# Compatibility shim generated by V111.8 final cover package.
# Canonical module: orchestration.skill_runtime.router.weights
from orchestration.skill_runtime.router.weights import *  # noqa: F401,F403
