# Compatibility shim generated by V111.8 final cover package.
# Canonical module: orchestration.skill_runtime.router.routing
from orchestration.skill_runtime.router.routing import *  # noqa: F401,F403
